spring.application.name=spring-boot-graphql

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:mydb_graphql}
spring.datasource.username=${POSTGRES_USER:myuser}
spring.datasource.password=${POSTGRES_PASSWORD:mypassword}
spring.jpa.hibernate.ddl-auto=create-drop

spring.jackson.time-zone=GMT+7
#spring.jackson.time-zone=Asia/Jakarta